### ISSUE TITLE
Changing model versions is onerous and error prone

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/model-config-tests#10]
In the process of changing model executables to spack deployed versions (or just changing between existing spack deployed versions) it has become clear that changing the full executable paths is onerous and somewhat error prone.

The paths are long and complicated. They need to be copied from the `spack.location` file of a deployment, and they are versioned for the model component code and so do not show the ACCESS-OM2 version from which they came. It is the `access-om2` package that contains the overall model versioning. For example, when updating to the deployment which introduced restart reproducibility all the model component versions were unchanged, though the build hashes were different, because they used an updated version of `spack-packages` and `spack-config`.

I think we should move to using generic model names (without paths) in the `exe` fields and use the module system to inject the correct directories into the `PATH` environment variable, e.g.

```yaml
model: ocean
   exe: fms_ACCESS-OM.x

...

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/linux-rocky8-cascadelake
  load:
      - access-om2/2023.03.0
```

This has a few benefits:
1. Ensures model components all come from the same deployment
1. Easier to switch between versions. Only the version in the loaded module is changed: this is good for users, but also for devs updating configs, and reviewers who can know the correct versions are being used
1. Makes configs more portable to other systems (future goal)

The rationale for using full paths was that it *less error prone*. I no longer think that is the case.

Note this would require this `payu` issue to be closed with an update

https://github.com/payu-org/payu/issues/379

Note also the details of how to specify the binary paths might depend on the final design of the `payu` update.

**Comment by CodeGat** [comment]
What is the status of this issue, given the above linked payu issue is merged?

**Comment by dougiesquire** [comment]
It is now substantially less onerous and requires only changing the version of the loaded module in the `config.yaml` - e.g. see [here](https://github.com/ACCESS-NRI/access-esm1.5-configs/pull/79/files#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034)

**Comment by aidanheerdegen** [comment]
I think we can call this solved.
