### ISSUE TITLE
Remove general config test for exe paths

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/model-config-tests#29]
In the eventual next release of payu, model executables can be set using modules. The current QA config tests check for absolute paths - and also that the exe paths are in the manifest: 

https://github.com/ACCESS-NRI/model-config-tests/blob/154705ee830c9a046dee5eb6903fb26126fc91c1/src/model_config_tests/test_config.py#L78-L109

These tests will either need to be removed or updated

**Comment by jo-basevi** [comment]
Note relevant issue here for updating these tests: https://github.com/ACCESS-NRI/model-config-tests/issues/18

**Comment by aidanheerdegen** [comment]
We're specify the versions of tests we use right? So we could make this change without need for backwards compatibility?

**Comment by jo-basevi** [comment]
Yes, we specify the version in the `<model>-configs` repository. So we should only now test that  exe paths are only set using modules?

**Comment by aidanheerdegen** [comment]
> So we should only now test that exe paths are only set using modules?

Yes.
