### ISSUE TITLE
Build virtual repro test environment on top of the payu conda environment

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/model-config-tests#37]
This CLEX CMS blog entry outlines how to build virtual environments on top of conda environments and retain access to all the packages: https://climate-cms.org/posts/2024-06-05-mixing-python-envs.html#virtual-environments

So it might be possible to create test virtual environments on top of a released `vk83` payu environment. This could reduce the size of environments used for reproducibility testing.

**Comment by anton-seaice** [comment]
Yes please - I would use this :)
