### ISSUE TITLE
ACCESS ESM1.5 CICE configuration

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/model-config-tests#50]
Once https://github.com/payu-org/payu/pull/483 has been merged, we should enforce (in QA checks) that esm1.5 configurations have a `ice_history.nml` file which contains an `icefields_nml` namelist. We also could enforce that `cice_in.nml` does not contain the `icefields_nml` namelist.

**Comment by aidanheerdegen** [comment]
Not just merged, but in a released `payu` deployment. When we have that can you ping this issue @jo-basevi? Thanks!
