### ISSUE TITLE
access-om3 tests

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/model-config-tests#7]
I [wrote a very simple `access-om3` model for these tests](https://github.com/dougiesquire/MOM6-CICE6/tree/main/test) when I was playing about with the repro CI workflows a month or so ago. Should I move this here, or is there still some dust that needs to settle?

**Comment by aidanheerdegen** [comment]
Make a PR and we can discuss details. @jo-basevi is best placed to advise if there are any structural requirements.
